/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:41a73090-9099-4271-888b-f53adac48d39",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_h00LLn0CW",
    "aws_user_pools_web_client_id": "4fo4adbav84i9iirqf5brstuuk",
    "oauth": {}
};


export default awsmobile;
